### ISSUE TITLE
DBC Issue on startup...

### ISSUE THREAD

**Issue by Shoxxo** [ProjectSkyfire/SkyFire.548#713]
```quote
Some required *.dbc files (1 from 149) not found or not compatible:
./dbc/SpellMisc.dbc exists, and has 25 field(s) (expected 26). Extracted file might be from wrong client version or a database-update has been forgotten.
```

I am 100% sure my clientversion are perfect!

**Comment by alterego21** [comment]
I'm 100% sure it's not.
On May 22, 2016 11:32 AM, "Shoxxo" <notifications@github.com> wrote:

Some required *.dbc files (1 from 149) not found or not compatible:
./dbc/SpellMisc.dbc exists, and has 25 field(s) (expected 26).
Extracted file might be from wrong client version or a database-update
has been forgotten.

I am 100% sure my clientversion are perfect!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/ProjectSkyfire/SkyFire.548/issues/713>

**Comment by Shoxxo** [comment]
i am sure it is latest 5.4.8 :) Trust me :)

**Comment by SkyFire** [comment]
Try and extract the DBC's again. Nothing has changed in the core.

**Comment by Shoxxo** [comment]
i tried 5 times self result i use debug x32

**Comment by alterego21** [comment]
You using a German client and dbc?
This could be an issue.

**Comment by Shoxxo** [comment]
Using enUS not enGB!

**Comment by Anddrw** [comment]
> Try and extract the DBC's again. Nothing has changed in the core.

That may be the problem. This project has 2% of the TrinityCore's community and team involvement, why? Because the latest commit was a copyright edit not even a small fix, if you would pay more interest in this project it could become a big "player" in the wow emulation world as there is no big pandaria source right now. I already know that whole quote about "we are not paid to do this, we have our own private life, we do not have that much time to work on the repo", and i agree with it, but if you start something you should keep it up or close it. Kind regards!

**Comment by alterego21** [comment]
Here is an idea. If you aren't going to supply anything stay out of it.

**Comment by Shoxxo** [comment]
Ehhh stop man, i have very big respect of you and your team. i deal with that that you have a privat life man ... :(

**Comment by Shoxxo** [comment]
Up ... nothing has been changed, extracting fails after patching the latest wow files... now it is db2 files outdated...

**Comment by alterego21** [comment]
Go on the forum and send me a PM with your skype. I will be home from work
in 6 hours.

**Comment by Shoxxo** [comment]
i can't i won a betakley :D i pay legion on http://www.twitch.tv/Texxhorntv

**Comment by Shoxxo** [comment]
Working on Fix :

8797d1ae69148972dfcc2e91d4516449721fbb91

edbe071209593040d4eb81c451a2bbadb4aa8451

**Comment by cybrann** [comment]
This is too late for an answer but the truth is, the problem lies within your launcher because your launcher is not 5.4.8 18414 version, it is 5.4.7 version, but it has been cracked to show that. HeroesWoW did that with their launcher. Only real 5.4.8 18414 version launcher can be downloaded from freakzwow.

If you ask yourself how do I know this? Well it's simple, size of your launcher is 12,844 KB while real size of the 5.4.8 18414 launcher should be 12,847 KB

**Comment by SkyFire** [comment]
We don't give a shit about illegal private servers that have modified clients. You need a clean unmodified 5.4.8 18414 to extract the maps and dbc's. You can google this.
